### ISSUE TITLE
pip install failing due to failure to find re

### ISSUE THREAD

**Issue by levi-rs** [russianidiot/get.py#3]
I get this when attempting to install `get` from PyPI:

```
(requestsTest) ➜  tmp pip install get
Collecting get
  Using cached get-0.0.12.tar.gz
Collecting re (from get)
  Could not find a version that satisfies the requirement re (from get) (from versions: )
No matching distribution found for re (from get)
```

**Comment by levi-rs** [comment]
@russianidiot get-0.0.14 is broken
```
Collecting get (from request)
  Downloading get-0.0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/53/x53ckqjs3jjgjc1bq1r_130w0000gn/T/pip-build-4k1qoh74/get/setup.py", line 2, in <module>
        from setupfiles import setup
    ImportError: No module named 'setupfiles'
```
